# Generated by Django 6.0 on 2025-12-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_evaluaciones', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=1000)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KarunaApp.docente')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPeriodo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_asistencia', models.FloatField()),
                ('valor_tarea', models.FloatField()),
                ('valor_participacion', models.FloatField()),
                ('valor_examen', models.FloatField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KarunaApp.grupo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KarunaApp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPeriodoAlumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asistencias', models.IntegerField()),
                ('tareas', models.IntegerField()),
                ('participaciones', models.IntegerField()),
                ('examen', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KarunaApp.alumno')),
                ('grupo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KarunaApp.grupoperiodo')),
            ],
        ),
    ]
