# Generated by Django 6.0 on 2025-12-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_evaluaciones', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('foto', models.CharField(max_length=1000)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='KarunaApp.docente')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_asistencia', models.FloatField()),
                ('valor_tarea', models.FloatField()),
                ('valor_participacion', models.FloatField()),
                ('valor_examen', models.FloatField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='KarunaApp.grupo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='KarunaApp.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='PromedioAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcial', models.PositiveIntegerField(blank=True, null=True)),
                ('promedio', models.FloatField()),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(default='Cierre de parcial', max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios', to='KarunaApp.alumno')),
                ('grupo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios', to='KarunaApp.grupoperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPeriodoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tareas', models.PositiveIntegerField(default=0)),
                ('participaciones', models.PositiveIntegerField(default=0)),
                ('examen', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='KarunaApp.alumno')),
                ('grupo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='KarunaApp.grupoperiodo')),
            ],
            options={
                'unique_together': {('grupo_periodo', 'alumno')},
            },
        ),
    ]
